name: Test

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: apt-get update && apt-get install libcriterion-dev

      - name: run test build
        run: ./build/test.sh
